### PR TITLE
add support peewee for flask #877

### PR DESCRIPTION
**Pull request by alexpantyukhin**

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
@omab  Hi, whats about this PR?

**Comment by omab** [comment]
Hi @alexpantyukhin , I need to dedicate some time to review this change, thanks!

**Comment by alexpantyukhin** [comment]
I see. I tested it on a couple of social networks.. It seems to be working. Thanks!

**Comment by omab** [comment]
Finally merged id. Thanks!

**Comment by alexpantyukhin** [comment]
You are welcome!

**Pull request merged**
