### PR TITLE
Tuple in pipeline's documentation should be ended with coma

### PR DESCRIPTION
**Pull request by JerzySpendel**
Just like in title.

### CODE REVIEW

**Comment by JerzySpendel** [comment]
Ok, that will be all I think.

**Comment by omab** [comment]
Why?

**Comment by JerzySpendel** [comment]
Tuples were ended with or without coma. I think all tuples should be ended with coma, or all tuples should be ended without a coma. That will be nicer

**Comment by vyscond** [comment]
probably related to this [concept](http://www.puppetcookbook.com/posts/trailing-commas.html)

**Comment by omab** [comment]
Personally I don't like trailing commas in ``tuples`` or ``dicts``, but this PR is harmless, so I'll accept it.

Thanks!

**Pull request merged**
