### PR TITLE
Fix Django 1.10 deprecation warnings

### LINKED ISSUE #804: Django 1.9.0 Deprecation Warning
I get the following deprecation warnings when starting the django development server with Python Social Auth app installed:

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:19: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got auth). Pass the callable instead.
  name='begin'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:21: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got complete). Pass the callable instead.
  name='complete'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:24: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got disconnect). Pass the callable instead.
  name='disconnect'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:26: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got disconnect). Pass the callable instead.
  .format(extra), 'disconnect', name='disconnect_individual'),

/usr/lib/tethys/local/lib/python2.7/site-packages/social/apps/django_app/urls.py:26: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  .format(extra), 'disconnect', name='disconnect_individual'),

### PR DESCRIPTION
**Pull request by yprez**
In django_app/urls.py:
* Use a list instead of `patterns`
* Use view callables instead of strings

Fixes #804, #754

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
:+1:

**Comment by gustavi** [comment]
The code is OK, somebody can merge it ?

**Comment by yprez** [comment]
@omab there are several PRs addressing this and other compatibility issues, is there any chance you can review/merge/close some of them?

**Comment by gustavi** [comment]
Some news ?

**Comment by omab** [comment]
Will take a look asap.

**Comment by gustavi** [comment]
?

It's just a code review, please merge it ASAP.

**Comment by omab** [comment]
Thanks @yprez, merged.

@gustavi it's not just "code review", and it also takes time.

**Comment by gustavi** [comment]
Thank you.

**Comment by yprez** [comment]
Thanks @omab !

I'll try fixing the other deprecation issues, or finding PRs that already do...

**Pull request merged**
