### PR TITLE
update for django 1.9

### PR DESCRIPTION
**Pull request by DanielJDufour**
Added some initialization code to a new ready method in the PythonSocialAuthConfig because of changes in Django.  See https://docs.djangoproject.com/en/1.7/ref/applications/ and https://docs.djangoproject.com/en/1.7/releases/1.7/.

I'm a big fan and feel free to disregard if you already got some code in the works.

Thank you!

### CODE REVIEW

**Comment by omab** [comment]
The code looks good and I like it, but I have some concerns about backward compatibility, maybe we can keep the code in the ``__init__.py`` with a version check to keep it compatible?

**Comment by omab** [comment]
I've implemented the mentioned change and merged the work. Thanks!

**Comment by DanielJDufour** [comment]
Thanks dude. If you're ever in DC, first round is on me!

**Comment by sohamnavadiya** [comment]
I am trying yo upgrade django 1.7 to 1.9.11 and after upgrade it, I am getting below error.



```
from social_django.models import AbstractUserSocialAuth, UserSocialAuth, Nonce, Association, Code, DjangoStorage
ImportError: No module named social_django.models

```

**Comment by omab** [comment]
@sohamnavadiya did you install the package `social-auth-django`?

**Comment by sohamnavadiya** [comment]
I have installed **social-auth-app-django (0.1.0)**
I fixed above error. But not I am getting below error.
```
 "INSTALLED_APPS." % (module, name)
RuntimeError: Model class social_django.models.UserSocialAuth doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

```

**Comment by omab** [comment]
@shepilov-vladislav, check the migration file https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md#django

**Comment by sohamnavadiya** [comment]
Now I am getting below exception strack.

```
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Documents/django_upgrade_venv/cubii_upgrade_1_9/local/lib/python2.7/site-packages/social_django/models.py", line 30, in <module>
    class AbstractUserSocialAuth(models.Model, DjangoUserMixin):
  File "/home/Documents/django_upgrade_venv/cubii_upgrade_1_9/local/lib/python2.7/site-packages/django/db/models/base.py", line 105, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/Documents/django_upgrade_venv/cubii_upgrade_1_9/local/lib/python2.7/site-packages/django/apps/registry.py", line 237, in get_containing_app_config
    self.check_apps_ready()
  File "/home/Documents/django_upgrade_venv/cubii_upgrade_1_9/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by sohamnavadiya** [comment]
I solved above issue. By the way thanks for quick reply. I really appreciate your work. Thanks

**Comment by omab** [comment]
@sohamnavadiya no problem, do you mind posting the solution, I know that transitions aren't always smooths and could be useful to somebody else experiencing the same problem.

**Pull request merged**
