### PR TITLE
Subclass MiddlewareMixin for Django 1.10 compat

### LINKED ISSUE #953: SocialAuthExceptionMiddleware needs updating to work with Django 1.10
If `social.apps.django_app.middleware.SocialAuthExceptionMiddleware` is added to Django 1.10's new (default) `MIDDLEWARE` setting (as opposed to `MIDDLEWARE_CLASSES`), Django will fail to start.  Ideally the middleware should be updated (using `django.utils.deprecation.MiddlewareMixin` in the short-term), and the documentation should be updated too.

Ref: https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware

### PR DESCRIPTION
**Pull request by jschneier**
Closes #953

### CODE REVIEW

**Comment by macolo** [comment]
@jschneier @omab is there a reason this PR cannot  be merged?

It is very, very dear to me. :)

**Comment by omab** [comment]
@macolo, the reason is that I'm in the middle of migrating the project to http://github.com/python-social-auth, I need to port the PRs there first.

**Comment by jschneier** [comment]
@omab Can we at least merge this and then people can install from git? I think this is one of the last blockers for a lot of people to move to the new `MIDDLEWARE` setting in Django. I see the ongoing migration to the split repos but realistically for now it doesn't look like people are using that.

**Comment by omab** [comment]
@jschneier, sure, we can do it

**Comment by tdruez** [comment]
@jschneier thanks for the fix :)

@omab would you mind to issue a new release including this? Thanks!

**Comment by tdruez** [comment]
@omab sorry to insist, but is there anything blocking a Django 1.10 compatible package?

**Comment by omab** [comment]
@tdruez, I'm porting the app to https://github.com/python-social-auth, I suggest using the git reference in the requirements.txt to get this fix since I don't plan any release on `python-social-auth` until I fully port it to depend on the new packages.

**Comment by tdruez** [comment]
Alright, good luck with the migration!

**Comment by danni** [comment]
If you don't want to run the Git version, here's a workaround until this is released.

```python
from django.utils.deprecation import MiddlewareMixin

import social.apps.django_app.middleware


class SocialAuthExceptionMiddleware(
        social.apps.django_app.middleware.SocialAuthExceptionMiddleware,
        MiddlewareMixin):
    """Work around Django 1.10 middleware incompatibility."""

    pass
```

**Pull request merged**
