### PR TITLE
Suppress deprecation warning, fixes #997

### LINKED ISSUE #997: RemovedInDjango110Warning: SubfieldBase has been deprecated.
Using 0.2.21 with Django 1.9, I get the following deprecation warning:

`RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.`

It looks like this was originally a problem and was fixed by #813. However, it looks like recently the warning was reintroduced, by this:

https://github.com/omab/python-social-auth/commit/03ae00154900a8150a5bf941663425698aacdb6b#diff-25f350079af94bedfb90b3a9e8cafb59R15

### PR DESCRIPTION
**Pull request by tom-dalton-fanduel**
Attempted fix for https://github.com/omab/python-social-auth/issues/997

### CODE REVIEW

**Comment by tom-dalton-fanduel** [comment]
Works for me on Django 1.9.9

**Comment by adamchainz** [comment]
👍  Would like to see this merged

**Comment by tom-dalton-fanduel** [comment]
Hi @omab, what do you think of this PR? It seems I'm not the only one affected by this. See #997 for the details but the TL;DR is that this was fixed by #813, but then subsequently broken again by 03ae001.

**Comment by omab** [comment]
I've ported this PR into [social-app-django](https://github.com/python-social-auth/social-app-django/commit/6384c13fc1d4431db7f218fa78a3aaf8e034b566).

Thanks!

**Pull request closed without merging**
