### PR TITLE
ChangeTip Backend

### PR DESCRIPTION
**Pull request by gorillamania**
Support for Login with ChangeTip, including docs.

https://www.changetip.com/api

### CODE REVIEW

**Comment by omab** [comment]
Merged. Thanks!

I've also made an small change, replaced the ``json.loads(urlopen(...))`` with the ``get_json()`` helper method that simplifies the task.

**Comment by gorillamania** [comment]
Thanks omab! 1 high five @changetip

**Comment by gorillamania** [comment]
Thanks @omab! 1 high five @changetip

**Comment by changetip** [comment]
Hi @omab, I've delivered a Bitcoin tip worth 1 high five (22,228 bits/$5.00) from @gorillamania to your ChangeTip wallet.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**

**Pull request merged**
