### PR TITLE
Added the ability to specify a pipeline on a per backend basis

### LINKED ISSUE #1016: Allow for per provider pipelines
Hi, 

I'm looking to customise my pipeline such that each provider has a slightly different pipeline. Rather than throwing in a bunch of `if` statements everywhere I thought it would be much better to be able to define a pipeline per provider.

For example `SOCIAL_AUTH_PIPELINE` would be the default pipeline which could be overridden by `SOCIAL_AUTH_GOOGLE_OAUTH2_PIPELINE`.

I'm happy to make a pull request for this if it is something that you would consider merging? Ideally I'd like to see it released fairly soon so that I can take advantage of it in my current project.

### PR DESCRIPTION
**Pull request by keattang**
Closes #1016

### CODE REVIEW

**Comment by keattang** [comment]
Closes #1016

**Comment by keattang** [comment]
@omab Is there a possibility of this being merged in? It's very simple and has been very useful in my project

**Comment by omab** [comment]
@keattang, sorry for the delays but I'm in the middle of transitioning `python-social-auth` to a more modular approach (almost done http://github.com/python-social-auth), next pending tasks involve migrating this repo to that organization, port PRs and Issues.

**Comment by omab** [comment]
I've ported this PR into [social-docs](https://github.com/python-social-auth/social-docs/commit/14a2467fe93589954114709aacecfc3c4eb8003d) and [social-core](https://github.com/python-social-auth/social-core/commit/0930a7d7d314c8256c446777222e3a6fda714203).

Thanks!

**Pull request closed without merging**
