### PR TITLE
Add a backend for Classlink.

### PR DESCRIPTION
**Pull request by youcandanch**
This pull request adds a backend for [Classlink](https://developer.classlink.com/docs/getting-started) - an SSO / rostering provider primarily used in K-12 education. It's been tested and verified working with their sandbox. It includes one small alteration to `set_extra_data` - extra data from Classlink came down as `unicode` and therefore was not caught by `isinstance(self.extra_data, str)`. I've changed it to check for all string types using `six`. 

Let me know if you have questions. Thank you!

### CODE REVIEW

**Comment by antinescience** [comment]
Hey @omab, just bumping this one a bit - we'd like to get this integration into production use for our service (https://github.com/newsela) in the next few days, so if you'd have any time to review and accept, I'd greatly appreciate it. Thank you!

**Comment by omab** [comment]
Thanks!

**Comment by antinescience** [comment]
No, thank _you_! I see there's a few other outstanding PRs with similar additive functionality - is the general release plan to merge similar things and then increment on PyPi? Just trying to gauge when it'll be available for consumption there.

**Comment by omab** [comment]
I'll try to get the new release out today, probably try to merge a few simple PRs before cutting it.

**Comment by staticshock** [comment]
❤️

**Comment by omab** [comment]
`v0.2.16` released to pypi.

**Comment by jpatel3** [comment]
Is there any documentation added for this backend? we also need to add this for our application, and I couldn't find the information here - https://python-social-auth.readthedocs.io/en/latest/backends/index.html

**Comment by omab** [comment]
This backend is not documented but it looks pretty standard OAuth2 flow, registering an application on their side and adding the settings on your project should do the trick.

**Comment by jpatel3** [comment]
@omab yes, I was able to add configuration on their side, but having some difficulty testing it locally before moving the change. I know its not related to python-social-auth, but @youcandanch do you have any tip to try out/test classlink integration locally?

**Pull request merged**
