### PR TITLE
Pulling JSONField from a third-party package

### PR DESCRIPTION
**Pull request by clintonb**
There isn't much value to having yet another implementation of JSONField in python-social-auth when plenty of others exist.  This commit replaces the JSONField implementation with that from the package jsonfield. jsonfield is an extra requirement as specifed in setup.py.

NOTE: This implementation of JSONField does not support Django 1.7 or below.

### CODE REVIEW

**Comment by clintonb** [comment]
Related: #908 and #909

**Comment by clintonb** [comment]
@webjunkie why the 👎 ?

**Comment by webjunkie** [comment]
@clintonb I'm just -1 on putting another dependency in this project. It might introduce other problems and looking at it, it wasn't updated all year and has "Django 1.8 support" as a feature. Just my two cents.

**Comment by omab** [comment]
Worth pointing that `django-jsonfield` is looking for a new maintainer for a while https://github.com/bradjasper/django-jsonfield/issues/146.

**Comment by omab** [comment]
I'm closing this since pulling a third-party that didn't got a maintainer for a while will make things complicated.

Thanks!

**Pull request closed without merging**
