### PR TITLE
Formatter fixes for SAML to support Py2.6

### PR DESCRIPTION
**Pull request by matburt**
This fix allows the SAML Backend to support Python 2.6

### CODE REVIEW

**Comment by chrismeyersfsu** [comment]
:+1: works with py2.6 for me.

**Comment by tkajtoch** [comment]
Clean commit.
Python 2.6 requires the `replacement_field` to be filled by the `field_name`.

Docs: https://docs.python.org/2.6/library/string.html#format-string-syntax

**Comment by matburt** [comment]
You can use {0} for positional arguments though (which is what is used here)... you just can't use the empty variant `{}`

**Comment by tkajtoch** [comment]
@matburt I know. My comment is just some kind of note for @omab to accept this PR quickly :-)

**Comment by matburt** [comment]
ah, gotcha!

**Comment by omab** [comment]
Sorry for the delay.

Thanks!

**Pull request merged**
