### PR TITLE
Update Facebook API version

### PR DESCRIPTION
**Pull request by charlesthk**
Updating v2.3 to current v2.5 version of facebook api

### CODE REVIEW

**Comment by tkajtoch** [comment]
Some critical errors occurred during the tests. This PR can't be merged.

**Comment by c-bata** [comment]
+1

Currently, latest facebook api version is v2.7.

**Comment by c-bata** [comment]
fixed by #798

**Comment by omab** [comment]
API version was recently changed to 2.7.

**Pull request closed without merging**
