### PR TITLE
GitHub Backend should deliver Username

### PR DESCRIPTION
**Pull request by rliebi**
The ID is a side product, a comment. The username is the real identifier.

### CODE REVIEW

**Comment by omab** [comment]
Where in the docs says that the id shouldn't be taken as the user identifier?

**Comment by rliebi** [comment]
There's no documented feature, nor undocumented ones that I know of, that expose the retrieval of the username from the id. From the GitHub API consumer perspective, the user id is an "implementation detail". The real key is the username.

**Comment by omab** [comment]
An ``id`` that can change, is not a valid way to identify a unique user ``id``. Anybody that changes his username won't be able to logging back to their account in your site.

You can retrieve the username using the ``/user`` API (https://developer.github.com/v3/users/#get-the-authenticated-user). Also, you can store it ``extra_data`` when defining the setting ``SOCIAL_AUTH_GITHUB_EXTRA_DATA = [('login', 'login')]`` (I've added that entry to the default value, so you won't need the setting actually). Then you can access it by doing ``user.social_auth.get(provider='github').extra_data['login']``.

**Comment by rliebi** [comment]
Okay. I agree with that😊

**Pull request closed without merging**
